name: Build and Upload Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev devscripts
        sudo apt-get install debhelper-compat=12

    - name: Build Debian package
      run: |
        dpkg-buildpackage -us -uc
        # Bewege das Debian-Paket in das Arbeitsverzeichnis des Runners
        mv ../cryptmaster_1.3_all.deb $HOME/debian-package.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: debian-package
        path: $HOME/debian-package.deb
