name: Build and Upload Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y dpkg-dev devscripts && sudo apt-get install debhelper-compat=12

    - name: Build Debian package
      run: |
        dpkg-buildpackage -us -uc

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: debian-package
        path: "../*.deb"  # Passe den Pfad entsprechend an, um das Debian-Paket im übergeordneten Verzeichnis zu erfassen
