name: Build and Upload Debian Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev devscripts
        sudo apt-get install debhelper-compat=12

    - name: Build Debian package
      run: |
        dpkg-buildpackage -us -uc
        # Bewege das Debian-Paket in das Arbeitsverzeichnis des Runners
        mv ../../*.deb $GITHUB_WORKSPACE

    - name: Find Debian package
      run: |
        DEB_FILE=$(find $GITHUB_WORKSPACE -type f -name '*.deb' -print -quit)
        echo "Debian package found at: $DEB_FILE"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: debian-package
        path: $DEB_FILE
